# Generated by Django 4.1.7 on 2023-04-03 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Apartment', 'Apartment'), ('Townhouse', 'Townhouse')], default='House', max_length=50)),
                ('sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_house', models.BooleanField(default=False)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('main_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('main_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('main_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('main_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('main_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('main_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
